#!/usr/bin/perl
use warnings;
use strict;
use Sound::Library;
use Term::ReadKey;
ReadMode 4;
  
########################################################################
#
# Copyright Simon Andrews 2016
#
# This file is part of RasbellyPi.
#
# RasbellyPi is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Foobar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with RasbellyPi.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################


############ DEBUG ################
# Set this to 1 to enable debugging
#
my $debug = 1;
###################################



my $library = Sound::Library -> new("Sounds");


# Main event loop

while (1) {

  # Check if bell is ringing

  if (defined (ReadKey(-1))) {
    # Play a sound
    $library -> play_sound();
    $debug and warn "Key was pressed\n";

    # Clear the buffer and see how impatient they are
    my $urgency_count = 0;
    while (defined (ReadKey(-1))) {
      ++$urgency_count;
    }

    if ($urgency_count > 2) {
      $debug and warn "They were impatient\n";
    }
    
    
  }
    

}





